{% set version = "1.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cubature
  version: {{ version|replace("-", "_") }}

source:
  fn: cubature_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/cubature_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/cubature/cubature_{{ version }}.tar.gz

  sha256: e4cca932af6255b448ceffe86966cc892379b0b8486d905fb9f84eb1d11aa2c1

build:
  number: 0
  # crashes with `gcc.exe: error: x64: No such file or directory`
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcpp
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('cubature')"  # [not win]
    - "\"%R%\" -e \"library('cubature')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/cubature/index.html
  license: GPL-3
  summary: R wrapper around the cubature C library of Steven G. Johnson for adaptive multivariate
    integration over hypercubes. This version provides both hcubature and pcubature
    routines in addition to a vector interface that results in substantial speed gains.
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
