{% set version = "1.3-13" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cubature
  version: {{ version|replace("-", "_") }}

source:
  fn: cubature_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/cubature_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/cubature/cubature_{{ version }}.tar.gz

  sha256: e33ff3be8c107cc3273e00c48536b5230448d438691c4b7d3c3b882676dc00ab

build:
  number: 0
  # crashes with `gcc.exe: error: x64: No such file or directory`
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcpp
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('cubature')"  # [not win]
    - "\"%R%\" -e \"library('cubature')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/cubature/index.html
  license: GPL-3
  summary: R wrapper around the cubature C library of Steven G. Johnson for adaptive multivariate
    integration over hypercubes. This version provides both hcubature and pcubature
    routines in addition to a vector interface that results in substantial speed gains.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
