travis:
  secure:
    BINSTAR_TOKEN: duV+NbIqN2kppk1clRzhp1KRZLebfVJcK1EN3sKXLJIwUuFBMWrElWM+1mKeGGpYNvMbgA/KjUc4crTYrIJPo1WeqiWt50dHGCMUVPfC/6aRMqcmo0SUoZEmaow3ZaSf3Lc0Kru+rXJpVJoUldo0zVVJbCmyxQHaW5vJhr3tiSxwV3LVKS2fYOfUytUycFuS8Ta/ER+sFaSV/OmKR7+cyXbFvTgTxz8Fi/hgDI1bBGhsVgUtaM0KIqAKAq6yERqX4EKAea4bTw8+ZuZqm2nDT1/zdm90amzD1lL6597TQlZyUrFT+ipX7IysH4NPuN7itOxhaeiV6PKT7XlFH9oTH0d6zMBlF1oaH+pdBoQqi2LKZH86pYjYHwlCQWbsqosEwxNqk5KY6/WNDqZ4OJnedknPCJy9CrlVvcgmMfPJ34SfOWtqCQEzd4RHWllPsaZ33UXFDPJApTrtz5hsRN54jGu1R8H6nqLg1rZbqK2Pze0QBDKpJi379kn1RvbxnMNhDUJ0+0D0NiZgGN43gnBZjGrstBJbnDTuENKtaFYQV/DhK8srMtkforHBL14vlnLSZAvKkye838zDJyq7JykZ7/CMxEueULYLbqT0S2sLM3McWQHWCjjBkAAUNx3YFUIZfMkcOteRhI+rMBV5UFKMhNp3kwbZkUvlFEaUyJP7jqc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
