appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 7FVTmti+faYsYwIQM8gR3MQgIfvKU7TQBOAcEuNWjf+zTxjCb8ym5hWUxgMGXlDpDe2oeEg5ZvpbmNxq7k+jyxOqqC+d7J7NHCWs3iGBL8dxiL5NaBaD0a26yeE5P09b8QLRii6m2kLUobm8HdCa6rDfqpc/pR+JlI10n63v8hrKO5LgZs3dUG9kWNX0xg4dA9louPWqQBh9Meehj24ny9SyKiWH0Ka37Y6G0f0qDJe3GM9huzRlwkWDZ/8I7DuJsGujj7SoX8IioIJHVna9CeHjGFha68w0u0uf+5C3IP7y3wMO27iRaw500BAuhewDsJpTERy9jzrJEYbh8Qja3WoIrQQ/6OT1osEO00X+KxUoVjSVlB0gBIk6DJ4QJm7fW1w6Yh3shVKqfC5FMgjTpVre4NTf5SgF0otQJbEQjwCLAAMPFCanANZNoVYIGKzJ1mglXu59mbYQZ4UKUFFCnq6v1lOByJ0xjb0rEZRloaMqpY9gWGzDWa13CSRIBC/IR8/8XzjObuVvnmHtBvk+aW4ICJB7WKfx+kC+dSgIzo+ZF2JX+HB9wxzZi5O5nmAlU8UKrvdnVpxVCqtMxgBW3M9gqQh72K3uTzEw1AZYOzXRSGYDXmRXqhFxph4ONbhp9A7FAsxYc3QOEV/I3foKSL6PfZXIj/0+QdKQ4OQqrBQ=
